### ISSUE TITLE
5.17.2

### ISSUE THREAD

**Issue by tildearrow** [agates/kwin-lowlatency-overlay#16]
Sorry for being late.

**Comment by Alexdegol** [comment]
Hello, I am not able to install your patch (v5.17.0). I followed these steps:


download stock KWin source and patch file: 
$ wget https://download.kde.org/stable/plasma/5.17.0/kwin-5.17.0.tar.xz
$ wget http://tildearrow.zapto.org/storage/kwin-lowlatency/kwin-lowlatency-5.17.0.patch
 
extract: 
$ tar -xvf kwin-5.17.0.tar.xz
 
patch: 
$ cd kwin-5.17.0
$ patch -p1 < ../kwin-lowlatency-5.17.0.patch
 
building 
Ubuntu 
Ubuntu uses a different library path, which means you’ll have to tweak the library dir: 
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_INSTALL_LIBEXECDIR=lib/x86_64-linux-gnu -DBUILD_TESTING=OFF
$ make
 
I use kubuntu 19.10, when I launch _cmake -DCMAKE etc._
I got back this:

**CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "/home/usr/kwin-5.17.0/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.**

**Comment by agates** [comment]
@Alexdegol this repository is for Gentoo only.

You'll have better luck opening an issue over at the main repo: https://github.com/tildearrow/kwin-lowlatency

**Comment by tildearrow** [comment]
@Alexdegol Thanks for pointing out! That was a mistake in the building instructions that I didn't fix to this day...
