### ISSUE TITLE
5.17.3 bump

### ISSUE THREAD

**Issue by archenroot** [agates/kwin-lowlatency-overlay#18]
Hi, thanks for this. Do you plan to push for 5.17.3 kwin? Or will current patches work with *.3 as they work for *.2 (I am not digging into plasma code ...)

**Comment by tildearrow** [comment]
No, sorry. There may not be KWin-lowlatency 5.17.3 after all.
I need to provide a rationale for this.

Two weeks ago, my ISP locked me out **again** (they did this one year ago but solved the problem quickly) by putting me under a carrier-grade NAT. This basically hinders anyone from accessing the website where the KWin-lowlatency patches are hosted.
agates cannot provide KWin-lowlatency 5.17.3 until the patches become available again.
This is my ISP's fault. Not only they put me under a carrier-grade NAT, but also they took IPv6 away from me! Now that is what you call regressing. Supposedly IPv6 was going to solve the address exhaustion problem.... but nope. They just went the easy way.

I am deeply sorry. I cannot provide patches anymore until I move out (which may happen tomorrow or maybe not).
And I do not have the money for dedicated business-grade Internet access. It costs like $100k per month, and I... how do you even expect me to afford that?

**Comment by agates** [comment]
@tildearrow is there any chance you could provide the parches by other means? Say, via github releases?
 
Regardless, my gentoo VM install is broken so this will take me some time to resolve anyway.

Nov 25, 2019 9:33:12 PM tildearrow <notifications@github.com>:

**Comment by tildearrow** [comment]
@agates I could try attachments... though you'll have to change the extension from txt to patch

[kwin-lowlatency-5.17.3.txt](https://github.com/agates/kwin-lowlatency-overlay/files/3889955/kwin-lowlatency-5.17.3.txt)

**Comment by agates** [comment]
> @agates I could try attachments... though you'll have to change the extension from txt to patch
> 
> [kwin-lowlatency-5.17.3.txt](https://github.com/agates/kwin-lowlatency-overlay/files/3889955/kwin-lowlatency-5.17.3.txt)

Thanks, I'll give this a shot once my install is ready to go.

**Comment by archenroot** [comment]
@tildearrow - or we can store in AWS S3 free tier - 5GB

**Comment by agates** [comment]
FYI I am very busy and can't get to this immediately...

It's easy to add the patch, and I can provide instructions if needed. Just lacking a working install to build and test, etc.

Nov 29, 2019 2:39:12 AM ArchenROOT <notifications@github.com>:

**Comment by agates** [comment]
Too late for this, but I have 5.17.4 now (#19).  5.17.5 coming up (#20).

**Comment by agates** [comment]
@tildearrow FYI I am just creating the patches myself using your patch script on the appropriate git tags you create there.
