### ISSUE TITLE
Provide ebuild for kwin-5.15.6

### ISSUE THREAD

**Issue by agates** [agates/kwin-lowlatency-overlay#2]
Upstream kwin-lowlatency has already supplied patches for 5.15.6 and provided them here (see #1).

Just waiting for vanilla kwin-5.15.6 packages to be rolled out in gentoo and updating the ebuild and manifest will be straightforward.

**Comment by tildearrow** [comment]
5.15.6 is an unofficial version.

**Comment by agates** [comment]
Was able to provide this as kwin-5.15.5-r1.

**Comment by realnc** [comment]
Installing this causes kwin to consume nearly 100% CPU on one core when there's movement on the desktop (especially when playing a video.) I had to revert.

**Comment by agates** [comment]
Can you report upstream to kwin-lowlatency please?

Tue Jun 11 03:45:09 CDT 2019 Nikos Chantziaras <notifications@github.com>:

**Comment by agates** [comment]
Yes I was confused, too, but there is no kwin-5.15.6 -- unless I'm misunderstanding something.  See here: https://github.com/KDE/kwin/commits/Plasma/5.15

@tildearrow, was this patch provided against a development version or should the 5.15.5 release work as intended?

**Comment by agates** [comment]
(Side note: I do not currently have a gentoo install to test and maintain this on, but will try to get one running in a virtual machine soon)

**Comment by tildearrow** [comment]
There is no Plasma 5.15.6 overall. Since 5.15.5 is the last official version of Plasma, I decided to continue any other fixes as unofficial version (e.g. 5.15.6). However, I have realized this was a mistake as the builds for other distros compile the whole Plasma instead of just KWin.

I have to go so can't write more

**Comment by realnc** [comment]
Fixed by reverting the "fix freezing" commit. Opened a bug here:

https://github.com/tildearrow/kwin-lowlatency/issues/17
