### ISSUE TITLE
Update to 5.16.1

### ISSUE THREAD

**Issue by tildearrow** [agates/kwin-lowlatency-overlay#4]

**Comment by tildearrow** [comment]
Also, I've noticed you switched to the lowercase style I use when writing README files. May you provide a rationale?

**Comment by agates** [comment]
I got a working Gentoo/KDE Plasma VM again last night so I can finally update these packages.  No longer using it as my main desktop, unfortunately.

**Comment by agates** [comment]
> Also, I've noticed you switched to the lowercase style I use when writing README files. May you provide a rationale?

I saw someone complain about the grammar in your repo and that really pissed me off, so I figured I'd try it here too.

**Comment by tildearrow** [comment]
I see. Thanks for the response. I'll be waiting for a release.

If you at some point become unable to maintain this overlay, please tell me and after I get an external hard drive (to free up some space) I'll be maintaining this overlay.
