### ISSUE TITLE
[Question] Did you thought about porting this to GURU overlay?

### ISSUE THREAD

**Issue by stkw0** [agates/kwin-lowlatency-overlay#52]
I think it may have more visibility if this is moved to GURU overlay. Or rather, what about porting it directly to official gentoo repository??

**Comment by agates** [comment]
I don't know the GURU overlay. I'm not opposed to -- nor could I prevent -- anyone from using this in another overlay or trying to upstream it in official Gentoo as a USE flag.

Personally, I don't have the time for it and just created this for personal use.  I believe there is an argument to be made to keeping this as its own overlay for those that don't want to bring in other packages.  But do with it what you will 🙂.
